# Generated by Django 3.1.3 on 2020-12-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201203_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users/profile_pic_default.png', upload_to='users'),
        ),
    ]
