# Generated by Django 3.1.3 on 2020-12-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201203_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='users/profile_pic_default.png', upload_to='users'),
        ),
    ]
