# Generated by Django 3.1.3 on 2020-12-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201205_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='users/profile_pic_default.png', upload_to='users'),
        ),
    ]
