# Generated by Django 3.1.3 on 2020-12-06 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('additional_info', models.TextField(blank=True)),
                ('baby_profile_picture', models.ImageField(upload_to='babies')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date_of_memory', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('memory_picture', models.ImageField(upload_to='memories')),
                ('kid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.kids')),
            ],
        ),
    ]
