# Generated by Django 3.1.3 on 2020-12-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_memory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='status',
            field=models.CharField(blank=True, choices=[('PRIVATE', 'Private'), ('SHARED', 'Shared'), ('PUBLIC', 'Public')], max_length=30),
        ),
    ]
